name: botlode_player
description: "Web player for BotsLode units."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: 2.5.1
  go_router: ^17.0.1
  google_fonts: ^6.2.1
  http: ^1.2.0
  intl: ^0.20.2
  rive: ^0.13.0
  riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  supabase_flutter: ^2.12.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4

  # Herramientas compatibles con la Zona Blindada
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_launcher_icons:

  android: false

  ios: false

  remove_alpha_ios: true

  image_path: "assets/icons/favicon.png"

  web:

    generate: true

    image_path: "assets/icons/favicon.png"

    background_color: "#000000"

    theme_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - .env
