name: botlode_player
description: "Web player for BotsLode units."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: 2.5.1
  google_fonts: ^6.2.1
  http: ^1.2.0
  rive: ^0.14.1
  riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4

  # Herramientas compatibles con la Zona Blindada
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - .env
