name: botlode_player
description: "Web player for BotsLode units."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- ZONA BLINDADA (NO TOCAR) ---
  # Estas versiones son las que funcionan con tu código actual.
  # Las fijamos para que no se rompan con un upgrade accidental.
  flutter_riverpod: 2.5.1  # Sin el ^ para fijar exacto (o permitir patch con ^2.5.1)
  riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  rive: 0.13.4             # La versión 0.14 rompe tu código, nos quedamos aquí.

  # --- ZONA LIBRE (PUEDEN ACTUALIZARSE) ---
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Herramientas compatibles con la Zona Blindada
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/ 
    - assets/images/
    - .env